controller_list:
#  - name: /robot/right_position_trajectory_controller
#  - name: /robot/right_velocity_trajectory_controller
  - name: /robot/limb/right
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - right_s0
      - right_s1
      - right_e0
      - right_e1
      - right_w0
      - right_w1
      - right_w2
#  - name: /robot/left_position_trajectory_controller
#  - name: /robot/left_velocity_trajectory_controller
  - name: /robot/limb/left
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - left_s0
      - left_s1
      - left_e0
      - left_e1
      - left_w0
      - left_w1
      - left_w2
  # - name: /robot/baxter_right_gripper_action
  #   action_ns: gripper_action
  #   type: GripperCommand
  #   default: true
  #   joints:
  #     - right_gripper_l_finger_joint
  # - name: /robot/baxter_left_gripper_action
  #   action_ns: gripper_action
  #   type: GripperCommand
  #   default: true
  #   joints:
  #     - left_gripper_l_finger_joint