controller_list:
  - name: /sdk/robot/limb/right
    ns: follow_joint_trajectory
    default: true
    joints:
      - right_s0
      - right_s1
      - right_e0
      - right_e1
      - right_w0
      - right_w1
      - right_w2
  - name: /sdk/robot/limb/left
    ns: follow_joint_trajectory
    default: true
    joints:
      - left_s0
      - left_s1
      - left_e0
      - left_e1
      - left_w0
      - left_w1
      - left_w2
