controller_list:
  - name: /robot/right_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - right_s0
      - right_s1
      - right_e0
      - right_e1
      - right_w0
      - right_w1
      - right_w2
  - name: /robot/left_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - left_s0
      - left_s1
      - left_e0
      - left_e1
      - left_w0
      - left_w1
      - left_w2
  - name: /robot/baxter_left_gripper_action
    action_ns: gripper_action
    type: GripperCommand
    default: true
    joints:
      - right_gripper_l_finger_joint
  - name: /robot/baxter_left_gripper_action
    action_ns: gripper_action
    type: GripperCommand
    default: true
    joints:
      - left_gripper_l_finger_joint