left_arm:
#  kinematics_solver: baxter_left_arm_kinematics/IKFastKinematicsPlugin
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.01
  kinematics_solver_timeout: 0.0001
  kinematics_solver_attempts: 1
right_arm:
#  kinematics_solver: baxter_right_arm_kinematics/IKFastKinematicsPlugin
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.01
  kinematics_solver_timeout: 0.0001
  kinematics_solver_attempts: 1