default_robot_padding: 0.0
default_robot_scale: 1.0
default_object_padding: 0.0
default_attached_padding: 0.0
default_robot_link_padding: {   
  "left_hand"                : &hand_padding 0.001,
  "left_hand_camera"         : 0.001,
  "left_hand_camera_axis"    : 0.001,
  "left_hand_range"          : 0.001,
  "left_gripper"             : *hand_padding,
  "left_gripper_l_finger"    : *hand_padding,
  "left_gripper_r_finger"    : *hand_padding,

  "right_hand"               : *hand_padding,
  "right_hand_camera"        : 0.001,
  "right_hand_camera_axis"   : 0.001,
  "right_hand_range"         : 0.001,
  "right_gripper"            : *hand_padding,
  "right_gripper_l_finger"   : *hand_padding,
  "right_gripper_r_finger"   : *hand_padding}