default_robot_padding: 0.08  # aka offset
default_robot_scale: 1.0
default_object_padding: 0.0
default_attached_padding: 0.0

# Scale is additive of the original link geometry size, same as padding_offset
default_robot_link_padding: {   
  "left_hand"                : &hand_padding 0.0,
  "left_hand_camera"         : *hand_padding,
  "left_hand_camera_axis"    : *hand_padding,
  "left_hand_range"          : *hand_padding,
  "left_gripper"             : *hand_padding,
  "left_gripper_l_finger"    : *hand_padding,
  "left_gripper_r_finger"    : *hand_padding,

  "right_hand"               : *hand_padding,
  "right_hand_camera"        : *hand_padding,
  "right_hand_camera_axis"   : *hand_padding,
  "right_hand_range"         : *hand_padding,
  "right_gripper"            : *hand_padding,
  "right_gripper_l_finger"   : *hand_padding,
  "right_gripper_r_finger"   : *hand_padding}

# Scale is multiplicative of the original link geometry size, same as padding_scale
default_robot_link_scale: {   
#  "left_hand"                : &hand_scale 0,
#  "left_hand_camera"         : *hand_scale}
}