  # Publish all joint states -----------------------------------

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Gazebo Sim - Right and Left Joint Effort Trajectory Controller -------------------

  left_joint_trajectory_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - left_s0
      - left_s1
      - left_e0
      - left_e1
      - left_w0
      - left_w1
      - left_w2

    constraints:
      goal_time: 0.5                   # Defaults to zero
      stopped_velocity_tolerance: 0.02 # Defaults to 0.01
      left_s0:
        trajectory: 0.05 # Not enforced if unspecified
        goal: 0.02       # Not enforced if unspecified
      left_s1:
        trajectory: 0.05 # Not enforced if unspecified
        goal: 0.02       # Not enforced if unspecified
      left_e0:
        trajectory: 0.05 # Not enforced if unspecified
        goal: 0.02       # Not enforced if unspecified
      left_e1:
        trajectory: 0.05 # Not enforced if unspecified
        goal: 0.02       # Not enforced if unspecified
      left_w0:
        trajectory: 0.05 # Not enforced if unspecified
        goal: 0.02       # Not enforced if unspecified
      left_w1:
        trajectory: 0.05 # Not enforced if unspecified
        goal: 0.02       # Not enforced if unspecified
      left_w2:
        trajectory: 0.05 # Not enforced if unspecified
        goal: 0.02       # Not enforced if unspecified

    gains: # Needed to map position+velocity commands to an effort command
      left_s0: {p: 700,  i: 0.01, d: 25, i_clamp: 1}
      left_s1: {p: 10000,  i: 100, d: 100, i_clamp: 1}
      left_e0: {p: 4500,  i: 35, d: 1, i_clamp: 1}
      left_e1: {p: 5500,  i: 60, d: 2, i_clamp: 1}
      left_w0: {p: 1000,  i: 30, d: 0.01, i_clamp: 1}
      left_w1: {p: 900,  i: 0.1, d: 0.01, i_clamp: 1}
      left_w2: {p: 1000,  i: 0.1, d: 0.01, i_clamp: 1}

    state_publish_rate:  25 # Defaults to 50
    action_monitor_rate: 10 # Defaults to 20
    hold_trajectory_duration: 0 # Defaults to 0.5

  right_joint_trajectory_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - right_s0
      - right_s1
      - right_e0
      - right_e1
      - right_w0
      - right_w1
      - right_w2

    constraints:
      goal_time: 0.5                   # Defaults to zero
      stopped_velocity_tolerance: 0.02 # Defaults to 0.01
      right_s0:
        trajectory: 0.05 # Not enforced if unspecified
        goal: 0.02       # Not enforced if unspecified
      right_s1:
        trajectory: 0.05 # Not enforced if unspecified
        goal: 0.02       # Not enforced if unspecified
      right_e0:
        trajectory: 0.05 # Not enforced if unspecified
        goal: 0.02       # Not enforced if unspecified
      right_e1:
        trajectory: 0.05 # Not enforced if unspecified
        goal: 0.02       # Not enforced if unspecified
      right_w0:
        trajectory: 0.05 # Not enforced if unspecified
        goal: 0.02       # Not enforced if unspecified
      right_w1:
        trajectory: 0.05 # Not enforced if unspecified
        goal: 0.02       # Not enforced if unspecified
      right_w2:
        trajectory: 0.05 # Not enforced if unspecified
        goal: 0.02       # Not enforced if unspecified

    gains: # Needed to map position+velocity commands to an effort command
      right_s0: {p: 700,  i: 0.01, d: 100, i_clamp: 1}
      right_s1: {p: 10000,  i: 100, d: 100, i_clamp: 1}
      right_e0: {p: 4500,  i: 35, d: 1, i_clamp: 1}
      right_e1: {p: 5500,  i: 60, d: 2, i_clamp: 1}
      right_w0: {p: 1000,  i: 30, d: 0.01, i_clamp: 1}
      right_w1: {p: 900,  i: 0.1, d: 0.01, i_clamp: 1}
      right_w2: {p: 1000,  i: 0.1, d: 0.01, i_clamp: 1}

    state_publish_rate:  25 # Defaults to 50
    action_monitor_rate: 10 # Defaults to 20
    hold_trajectory_duration: 0 # Defaults to 0.5
